{% set name = "pychromecast" %}
{% set version = "14.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fe78841b0b04aa107d08aed216e91ab9cfb54b11d089d382be4e987e3631d4a6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - protobuf >=3.19.1,<4
    - zeroconf >=0.25.1
    - casttube >=0.2.0

test:
  imports:
    - pychromecast
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/balloob/pychromecast
  summary: Python module to talk to Google Chromecast.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
