{% set name = "pychromecast" %}
{% set version = "13.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyChromecast-{{ version }}.tar.gz
  sha256: 1b520e477492cd8fe022e4d041e676056d5fffbb6c05b2f4509801a06bc67bec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - protobuf >=3.19.1,<4
    - zeroconf >=0.25.1
    - casttube >=0.2.0

test:
  imports:
    - pychromecast
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/balloob/pychromecast
  summary: Python module to talk to Google Chromecast.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
