{% set name = "pychromecast" %}
{% set version = "13.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyChromecast-{{ version }}.tar.gz
  sha256: 08e61a8b54bd2119d3c9ab1ec0136d3d8563aa97e0a3b57841588b9be60c2676

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - protobuf >=3.19.1,<4
    - zeroconf >=0.25.1
    - casttube >=0.2.0

test:
  imports:
    - pychromecast
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/balloob/pychromecast
  summary: Python module to talk to Google Chromecast.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
