schema_version: 1

context:
  version: "14.0.10"
  python_min: "3.11"

package:
  name: pychromecast
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pychromecast/pychromecast-${{ version }}.tar.gz
  sha256: f05a1c8d727d4f104c8c731688053033e05157f2ab81bc8eef50ec0c62f9373c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - protobuf >=4.25.1
    - zeroconf >=0.25.1
    - casttube >=0.2.0

tests:
  - python:
      pip_check: true
      imports:
        - pychromecast
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Python module to talk to Google Chromecast.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/balloob/pychromecast

extra:
  recipe-maintainers:
    - pavelzw
